// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using IntegrationQA;
//
//    var author = Author.FromJson(jsonString);

namespace IntegrationQA.Models
{
    using Newtonsoft.Json;
    using System;

    public partial class ResponseAuthor
    {
        [JsonProperty("id")]
        public Guid Id { get; set; }

        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("age")]
        public long Age { get; set; }

        [JsonProperty("genre")]
        public string Genre { get; set; }
    }

    public partial class ResponseAuthor
    {
        public static ResponseAuthor FromJson(string json) => JsonConvert.DeserializeObject<ResponseAuthor>(json, Converter.Settings);
    }
}
